# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JTM1nmgK7NZjm8QgZLa7NNtXifr_UDHa

<h1>4 Python Libraries

<h2>1. pyforest
"""

!pip install pyforest

from pyforest import *
lazy_imports()

"""<h2>2. Emot"""

!pip install emot
import emot
m="🙀🙀🙀"
v=emot.emoji(m)
v

"""## <h2> 3.Dabl

Dabl aims to make machine learning modeling more accessible for beginners.

Dabl iterated through multiple models, including Dummy Classifier, GaussianNB, Decision Trees with different depths, and Logistic Regression.
"""

!pip install dabl
import dabl

df= pd.read_csv('/content/drive/MyDrive/hasy-data-labels.csv')
df

X, y = load_digits(return_X_y=True)
# Splitting the dataset into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)
# Calling the model
sc = dabl.SimpleClassifier().fit(X_train, y_train)
# Evaluating accuracy score
print("Accuracy score", sc.score(X_test, y_test))

dabl.plot(df,'latex')

"""<h2> 4.SweetViz

Sweetviz is a low-code Python library that generates beautiful visualizations to kickstart your exploratory data analysis with two lines of code. The output is an interactive HTML file.
"""

!pip install sweetviz
import sweetviz as sv
my_report = sv.analyze(df)
my_report.show_html()